services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streaming-cache-server
    ports:
      - "50051:50051"
    env_file:
      - .env
    restart: unless-stopped
    