version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streaming-cache-server
    ports:
      - "50051:50051"
    environment:
      - REDIS_ADDR=${REDIS_ADDR}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: unless-stopped